// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"quasiInput","status":true,"description":"Adds additional keys to Input class, and allows remapping keys.","parameters":{"Ok":"#enter, #space, #z","Escape / Cancel":"#esc, #insert, #x, #num0","Shift":"#shift, #cancel","Control":"#ctrl, #alt","Tab":"#tab","Pageup":"#pageup, #q","Pagedown":"#pagedown, #w","Left":"#left, #num4","Right":"#right, #num6","Up":"#up, #num8","Down":"#down, #num2","Debug":"#f9","===========":"","FPS":"f2","Streched":"f3","FullScreen":"f4","Restart":"f5","Console":"f8"}},
{"name":"GALV_EventSpawner","status":false,"description":"Spawn events from a specified spawn map to a desired location.","parameters":{"Spawn Map Id":"MAP001"}},
{"name":"OrangeMoveCharacterTo","status":true,"description":"This plugin adds a script call and a plugin command you can use to move the player or an event to a specific position.","parameters":{"failedMovementDelay":"30"}},
{"name":"factions","status":true,"description":"","parameters":{"Factions":"Factions.json"}},
{"name":"test","status":true,"description":"","parameters":{"Factions":""}},
{"name":"GALV_MessageStyles","status":true,"description":"Settings to change how your \"Show Text\" messages look as well as code to make them floating.","parameters":{"Input Indicator":"2,0,-12","Indicator Zoom":"100","Message Padding":"0,0,0,0","Message Windowskin":"Window","Arrow Graphic":"WindowArrow","Windowskin Back Opacity":"192","Y Offset":"60","Font":"","Font Filename":"","Font Outline":"true","Font Size":"28"}}
];
